### ISSUE TITLE
Tournament Standings/Results

### ISSUE THREAD

**Issue by ebshimizu** [ebshimizu/soothsayer-2#19]
- [x] erbs: scoreboard format
- [x] erbs: scoreboard automatic updating
- [x] erbs: scoreboard overlay
- [x] erbs: overlay styles
- [x] erbs: import from table

**Comment by Crowverlay** [comment]
[ERBS_Scoreboard.zip](https://github.com/ebshimizu/soothsayer-2/files/6131691/ERBS_Scoreboard.zip)
